name: Update and Push to Github
on: push
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        steps:
            - uses: actions/checkout@v1
            - name: Fetch resources
              run: echo "Test" >> README.md

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: README.md
                  commit-msg: Update README
                  github-token: ${{ secrets.CI_TOKEN }}

