name: Update and Push to Github
on: 
    repository_dispatch:
        types: [push]
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1

            - name: Fetch resources
              run: echo "Test" >> README.md

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: README.md
                  commit-msg: Update resources
                  github-token: ${{ secrets.CI_TOKEN }}

