name: Variables
on:
  push:

jobs:
  run-github-actions:
    name: Run Github Actions
    runs-on: ubuntu-20.04
    steps:
      - name: Step 1
        id: step1
        run: echo "Step 1"

      - name: Step 2
        id: step2
        run: echo "Step 2"

      - name: Step 3
        id: step3
        run: echo "Step 3"

      - name: Store result
        run: |
          out=$( steps.step1.outcome == "success" && steps.step2.outcome == "success" && steps.step3.outcome == "success" )
          echo "OUT=$out" >> $GITHUB_ENV

      - name: Print
        run: echo $OUT

