name: Variables
on:
  push:

jobs:
  run-github-actions:
    name: Run Github Actions
    runs-on: ubuntu-20.04
    steps:
      - name: Step 1
        id: step1
        run: echo "Step 1"

      - name: Step 2
        id: step2
        run: echo "Step 2"

      - name: Step 3
        id: step3
        run: echo "Step 3"

      - name: Store result
        run: |
          out1=$( [ "${{ steps.step1.outcome }}" == "success" ] )
          out2=$( [ "${{ steps.step2.outcome }}" == "success" ] && [ "${{ steps.step3.outcome }}" == "success" ] )
          out=echo $out1 && $out2 && echo true || echo false          
          echo "OUT=$out" >> $GITHUB_ENV

      - name: Debug step 1 outcome
        run: |
          echo "Step 1 outcome: ${{ steps.step1.outcome }}"

      - name: Debug step 2 outcome
        run: |
          echo "Step 2 outcome: ${{ steps.step2.outcome }}"

      - name: Debug step 3 outcome
        run: |
          echo "Step 3 outcome: ${{ steps.step3.outcome }}"

      - name: Print
        run: echo $OUT
