name: Default Github Environment Variables
on: [push]

jobs:
  github-actions-environment-variables-ubuntu:
    name:  List of GitHub Actions Env Variables on Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: List
        run: env
      #- name: Clone
      #  run: |
      #    git clone git@github:$GITHUB_REPOSITORY
      #    git checkout $GITHUB_SHA

