name: Schedule Actions Workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 1 *"

jobs:
    github-actions-sechedule:
      name:  List of GitHub Actions Env Variables on Ubuntu 20.04
      runs-on: ubuntu-latest
      steps:
        - name: List
          run: env
