name: User Defined Env Vars

on: [push]

env:
	GLOBAL_ENV: global_env

jobs:
  log-env:
    name: Log Env
    runs-on: ubuntu-18.04
    steps:
      - name: Global Variable
        run: |
          echo "Global env: ${GLOBAL_ENV}"
