name: User Defined Env Vars

on: [push]


env:
  GLOBAL_FOLDER: /global/

jobs:
  log-env:
    name: Log Env
    runs-on: ubuntu-18.04
    steps:
      - name: Global Variable
        run: |
          ls -a
