name: Share Variable Across Jobs
on: push

jobs:
  Job1:
    name: Run Github Actions
    runs-on: ubuntu-20.04
    steps:
      - name: Record Time-stamp
        run: |
          export TIME_STAMP=$(date +%Y%m%d)_$(date +%H%M%S)
          echo "{TIME_STAMP}=${TIME_STAMP}" >> $GITHUB_ENV
  Job2:
    name: Print Time-stamp
    runs-on: ubuntu-latest
    needs: [Job1]
    steps:
      - name: Print
        run: |
            echo "${{ env.TIME_STAMP }}"
